rules/urls.py
"""
Copyright(C) 2014-2018, Stamus Networks
Written by Eric Leblond <eleblond@stamus-networks.com>

This file is part of Scirius.

Scirius is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Scirius is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Scirius.  If not, see <http://www.gnu.org/licenses/>.
"""

from __future__ import unicode_literals
from django.conf.urls import url

from rules import views

urlpatterns = [
    url(r'^$', views.index, name='rules_index'),
    url(r'^about/$', views.about, name='scirius_about'),
    url(r'^search$', views.search, name='scirius_search'),
    url(r'^es$', views.elasticsearch, name='elasticsearch'),
    url(r'^settings/$', views.system_settings, name='system_settings'),
    url(r'^source/$', views.sources, name='sources'),
    url(r'^source/add$', views.add_source, name='add_source'),
    url(r'^source/add_public$', views.add_public_source, name='add_public_source'),
    url(r'^source/update_public$', views.update_public_sources, name='update_public_sources'),
    url(r'^source/(?P<source_id>\d+)/$', views.source, name='source'),
    url(r'^source/(?P<source_id>\d+)/update$', views.update_source, name='update_source'),
    url(r'^source/(?P<source_id>\d+)/diff$', views.diff_source, name='diff_source'),
    url(r'^source/(?P<source_id>\d+)/changelog', views.changelog_source, name='changelog_source'),
    url(r'^source/(?P<source_id>\d+)/edit$', views.edit_source, name='edit_source'),
    url(r'^source/(?P<source_id>\d+)/delete$', views.delete_source, name='delete_source'),
    url(r'^source/(?P<source_id>\d+)/activate/(?P<ruleset_id>\d+)$', views. activate_source, name='activate_source'),
    url(r'^source/(?P<source_id>\d+)/test$', views.test_source, name='test_source'),
    url(r'^sourceupdate/(?P<update_id>\d+)$', views.sourceupdate, name='sourceupdate'),
    url(r'^category/$', views.categories, name='categories'),
    url(r'^category/(?P<cat_id>\d+)/$', views.category, name='category'),
    url(r'^category/(?P<cat_id>\d+)/disable$', views.disable_category, name='disable_category'),
    url(r'^category/(?P<cat_id>\d+)/enable$', views.enable_category, name='enable_category'),
    url(r'^category/(?P<cat_id>\d+)/transform$', views.transform_category, name='transform_category'),
    url(r'^ruleset/$', views.rulesets, name='rulesets'),
    url(r'^ruleset/add$', views.add_ruleset, name='add_ruleset'),
    url(r'^ruleset/(?P<ruleset_id>\d+)/$', views.ruleset, name='ruleset'),
    url(r'^ruleset/(?P<ruleset_id>\d+)/update$', views.update_ruleset, name='update_ruleset'),
    url(r'^ruleset/(?P<ruleset_id>\d+)/edit$', views.edit_ruleset, name='edit_ruleset'),
    url(r'^ruleset/(?P<ruleset_id>\d+)/delete$', views.delete_ruleset, name='delete_ruleset'),
    url(r'^ruleset/(?P<ruleset_id>\d+)/addsupprule$', views.ruleset_add_supprule, name='addsupprule'),
    url(r'^ruleset/(?P<ruleset_id>\d+)/display$', views.ruleset, {'mode': 'display'}, name='display_ruleset'),
    url(r'^ruleset/(?P<ruleset_id>\d+)/export$', views.ruleset, {'mode': 'export'}, name='export_ruleset'),
    url(r'^ruleset/(?P<ruleset_id>\d+)/copy$', views.copy_ruleset, name='copy_ruleset'),
    url(r'^ruleset/(?P<ruleset_id>\d+)/changelog', views.changelog_ruleset, name='changelog_ruleset'),
    url(r'^ruleset/(?P<ruleset_id>\d+)/test', views.test_ruleset, name='test_ruleset'),
    url(r'^rule/(?P<rule_id>\d+)/disable$', views.disable_rule, name='disable_rule'),
    url(r'^rule/(?P<rule_id>\d+)/enable$', views.enable_rule, name='enable_rule'),
    url(r'^rule/(?P<rule_id>\d+)/delete$', views.delete_alerts, name='delete_alerts'),
    url(r'^rule/(?P<rule_id>\d+)/availability$', views.toggle_availability, name='toggle_availability'),
    url(r'^rule/(?P<rule_id>\d+)/edit$', views.edit_rule, name='edit_rule'),
    url(r'^rule/(?P<rule_id>\d+)/threshold$', views.threshold_rule, name='threshold_rule'),
    url(r'^rule/(?P<rule_id>\d+)/comment$', views.comment_rule, name='comment_rule'),
    url(r'^rule/pk/(?P<rule_id>\d+)/$', views.rule, {'key': 'pk'}, name='rule'),
    url(r'^rule/(?P<rule_id>\d+)/$', views.rule, {'key': 'sid'}, name='rule_sid'),
    url(r'^rule/pk/(?P<rule_id>\d+)/test/(?P<ruleset_id>\d+)$', views.test_rule, {'key': 'pk'}, name='test_rule'),
    url(r'^info$', views.info, name='info'),
    url(r'^threshold/(?P<threshold_id>\d+)/$', views.threshold, name='threshold'),
    url(r'^threshold/(?P<threshold_id>\d+)/delete$', views.delete_threshold, name='delete_threshold'),
    url(r'^threshold/(?P<threshold_id>\d+)/edit$', views.edit_threshold, name='edit_threshold'),
    url(r'^history$', views.history, name='history'),
    url(r'^comment$', views.history, name='comment'),
    url(r'^comment/(?P<comment_id>\d+)/delete$', views.delete_comment, name='delete_comment'),
    url(r'^hunt$', views.hunt, name='hunt'),
]

scirius/urls.py
from __future__ import unicode_literals
from django.conf.urls import url, include
from django.conf import settings

from views import homepage, KibanaProxyView, EveboxProxyView, MolochProxyView
from rest_api import router

urlpatterns = [
    url(r'^rules/', include('rules.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^viz/', include('viz.urls')),
    url(r'^'+ settings.RULESET_MIDDLEWARE + '/', include('' + settings.RULESET_MIDDLEWARE + '.urls')),
    url(r'^rest/', include(router.urls)),
    url('^$', homepage),
    # Forward "app/kibana.*" to kibana (work around to https://github.com/elastic/kibana/issues/5230)
    url(r'^(?P<path>app/.*)$', KibanaProxyView.as_view()),
    url(r'^(?P<path>status.*)$', KibanaProxyView.as_view()),
    url(r'^(?P<path>api.*)$', KibanaProxyView.as_view()),
    url(r'^(?P<path>plugins.*)$', KibanaProxyView.as_view()),
    # Forward timelion plugin
    url(r'^(?P<path>timelion/.*)$', KibanaProxyView.as_view()),
    url(r'^(?P<path>bundles/.*)$', KibanaProxyView.as_view()),
    url(r'^(?P<path>elasticsearch/.*)$', KibanaProxyView.as_view()),
    url(r'^kibana/(?P<path>.*)$', KibanaProxyView.as_view()),
    url(r'^evebox/(?P<path>.*)$', EveboxProxyView.as_view()),
    # Kibana 5.2 specific
    url(r'^(?P<path>ui/fonts.*)$', KibanaProxyView.as_view()),
    url(r'^(?P<path>es_admin.*)$', KibanaProxyView.as_view()),

    # Moloch proxy
    url(r'^moloch/(?P<path>.*)$', MolochProxyView.as_view()),
]

viz/urls.py
"""
Copyright(C) 2018, Stamus Networks
Written by Eric Leblond <eleblond@stamus-networks.com>

This file is part of Scirius.

Scirius is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Scirius is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Scirius.  If not, see <http://www.gnu.org/licenses/>.
"""

from __future__ import unicode_literals
from django.conf.urls import url, include

from viz import views

urlpatterns = [
    url(r'^dashboard$', views.dashboard, name='viz_dashboard'),
    url(r'^dashboard_target$', views.dashboard_target, name='viz_target_dashboard'),
    url(r'^pktcity$', views.pktcity, name='viz_pktcity'),
    ]

rules/forms.py
"""
Copyright(C) 2014, Stamus Networks
Written by Eric Leblond <eleblond@stamus-networks.com>

This file is part of Scirius.

Scirius is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Scirius is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Scirius.  If not, see <http://www.gnu.org/licenses/>.
"""

from __future__ import unicode_literals
from django import forms
from django.utils import timezone
from django.conf import settings
from django.core.exceptions import NON_FIELD_ERRORS
from rules.models import Ruleset, Rule, Source, Category, SourceAtVersion, SystemSettings, Threshold, UserAction, Transformation


class CommentForm(forms.Form):
    comment = forms.CharField(widget=forms.Textarea,
                              label = "Optional comment",
                              required = False)

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)

        # Put the comment field at the end of the self.fields ordered dict
        comment = self.fields.pop('comment')
        self.fields['comment'] = comment

class RulesetChoiceForm(CommentForm):
    rulesets = forms.ModelMultipleChoiceField(None,
                        widget=forms.CheckboxSelectMultiple(),
                        required=True)

    def __init__(self, *args, **kwargs):
        super(RulesetChoiceForm, self).__init__(*args, **kwargs)
        ruleset_list =  Ruleset.objects.all()
        self.fields['rulesets'].queryset = ruleset_list

        if hasattr(self, 'rulesets_label'):
            self.fields['rulesets'].label = self.rulesets_label

        if not len(ruleset_list):
            if not (isinstance(self, AddSourceForm) or isinstance(self, AddPublicSourceForm)):
                self.errors[NON_FIELD_ERRORS] = ['Please create a ruleset first']
            self.fields.pop('rulesets')

class SystemSettingsForm(forms.ModelForm, CommentForm):
    use_http_proxy = forms.BooleanField(label='Use a proxy', required=False)
    custom_elasticsearch = forms.BooleanField(label='Use a custom Elasticsearch server', required=False)
    http_proxy = forms.CharField(max_length=200, required=False, help_text='Proxy address of the form "http://username:password@hostname:port/"')
    elasticsearch_url = forms.CharField(max_length=200, empty_value='http://elasticsearch:9200/', required=False)

    class Meta:
        model = SystemSettings
        exclude = []

class KibanaDataForm(forms.Form):
    file = forms.FileField(required = False)

class SourceForm(forms.ModelForm, CommentForm):
    file = forms.FileField(required = False)
    authkey = forms.CharField(max_length=100,
                              label = "Optional authorization key",
                              required = False,
                              widget = forms.PasswordInput(render_value = True))
    class Meta:
        model = Source
        exclude = ['created_date', 'updated_date', 'cats_count', 'rules_count', 'public_source']

    def __init__(self, *args, **kwargs):
        source = kwargs.get('instance', None)
        super(SourceForm, self).__init__(*args, **kwargs)

        from scirius.utils import get_middleware_module
        choices = get_middleware_module('common').update_source_content_type(Source.CONTENT_TYPE, source)
        self.fields['datatype'] = forms.ChoiceField(choices=choices)


class AddSourceForm(forms.ModelForm, RulesetChoiceForm):
    file  = forms.FileField(required = False)
    authkey = forms.CharField(max_length=100,
                              label = "Optional authorization key",
                              required = False)
    rulesets_label = "Add source to the following ruleset(s)"

    class Meta:
        model = Source
        exclude = ['created_date', 'updated_date', 'cats_count', 'rules_count', 'public_source', 'version']

    def __init__(self, *args, **kwargs):
        super(AddSourceForm, self).__init__(*args, **kwargs)
        if 'rulesets' in self.fields:
            self.fields['rulesets'].required =  False

        from scirius.utils import get_middleware_module
        choices = get_middleware_module('common').update_source_content_type(Source.CONTENT_TYPE)
        self.fields['datatype'] = forms.ChoiceField(choices=choices)


class AddPublicSourceForm(forms.ModelForm, RulesetChoiceForm):
    source_id = forms.CharField(max_length=100)
    secret_code = forms.CharField(max_length=100, required = False)
    use_iprep = forms.BooleanField(required=False)

    class Meta:
        model = Source
        exclude = ['created_date', 'updated_date', 'cats_count', 'rules_count', 'method', 'datatype', 'version']

    def __init__(self, *args, **kwargs):
        super(AddPublicSourceForm, self).__init__(*args, **kwargs)
        if 'rulesets' in self.fields:
            self.fields['rulesets'].required =  False

# Display choices of SourceAtVersion
class RulesetForm(CommentForm):
    name = forms.CharField(max_length=100)
    sources = forms.ModelMultipleChoiceField(None, widget=forms.CheckboxSelectMultiple())
    activate_categories = forms.BooleanField(label = "Activate all categories in selected sources",
                                             initial = True, required = False)

    rulesets_label = "Apply transformation(s) to the following ruleset(s)"
    action = forms.ChoiceField()
    lateral = forms.ChoiceField()
    target = forms.ChoiceField()


    def create_ruleset(self):
        ruleset = Ruleset.objects.create(name = self.cleaned_data['name'],
                    created_date = timezone.now(),
                    updated_date = timezone.now(),
                    )
        for src in self.cleaned_data['sources']:
            ruleset.sources.add(src)
            if self.cleaned_data['activate_categories']:
                for cat in Category.objects.filter(source = src.source):
                    ruleset.categories.add(cat)
        return ruleset

    def __init__(self, *args, **kwargs):
        super(RulesetForm, self).__init__(*args, **kwargs)
        sourceatversion = SourceAtVersion.objects.all()
        self.fields['sources'].queryset = sourceatversion
        self.fields['action'].choices = Ruleset.get_transformation_choices(key=Transformation.ACTION)
        self.fields['lateral'].choices = Ruleset.get_transformation_choices(key=Transformation.LATERAL)
        self.fields['target'].choices = Ruleset.get_transformation_choices(key=Transformation.TARGET)


class RulesetEditForm(forms.ModelForm, CommentForm):
    name = forms.CharField(max_length=100)

    rulesets_label = "Apply transformation(s) to the following ruleset(s)"
    action = forms.ChoiceField()
    lateral = forms.ChoiceField()
    target = forms.ChoiceField()

    class Meta:
        model = Ruleset
        fields = ('name', 'action', 'lateral', 'target')

    def __init__(self, *args, **kwargs):
        super(RulesetEditForm, self).__init__(*args, **kwargs)
        self.fields['action'].choices = Ruleset.get_transformation_choices(key=Transformation.ACTION)
        self.fields['lateral'].choices = Ruleset.get_transformation_choices(key=Transformation.LATERAL)
        self.fields['target'].choices = Ruleset.get_transformation_choices(key=Transformation.TARGET)


class RulesetCopyForm(CommentForm):
    name = forms.CharField(max_length=100)

class RulesetSuppressForm(RulesetChoiceForm):
    rulesets_label = "Modify object in the following ruleset(s)"

class AddRuleThresholdForm(forms.ModelForm, RulesetChoiceForm):
    rulesets_label = "Add threshold to the following ruleset(s)"
    threshold_type = forms.CharField(widget = forms.HiddenInput())
    class Meta:
        model = Threshold
        exclude = ['ruleset', 'rule', 'gid', 'descr', 'net']

class AddRuleSuppressForm(forms.ModelForm, RulesetChoiceForm):
    rulesets_label = "Add suppression to the following ruleset(s)"
    threshold_type = forms.CharField(widget = forms.HiddenInput())
    class Meta:
        model = Threshold
        exclude = ['ruleset', 'rule', 'gid', 'descr', 'type', 'count', 'seconds']

    def clean(self):
        cleaned_data = super(AddRuleSuppressForm, self).clean()
        if 'net' in cleaned_data and ',' in cleaned_data['net']:
            cleaned_data['net'] = ','.join([item.strip() for item in cleaned_data['net'].split(',')])


class EditThresholdForm(forms.ModelForm, CommentForm):
    class Meta:
        model = Threshold
        exclude = ['pk', 'rule']

class RuleTransformForm(RulesetChoiceForm):
    rulesets_label = "Apply transformation(s) to the following ruleset(s)"
    action = forms.ChoiceField()
    lateral = forms.ChoiceField()
    target = forms.ChoiceField()

    def __init__(self, *args, **kwargs):
        rule = kwargs.pop('instance')

        super(RuleTransformForm, self).__init__(*args, **kwargs)
        choices = rule.get_transformation_choices(key=Transformation.ACTION)
        self.fields['action'].choices = choices
        self.fields['lateral'].choices = rule.get_transformation_choices(key=Transformation.LATERAL)
        self.fields['target'].choices = rule.get_transformation_choices(key=Transformation.TARGET)


class CategoryTransformForm(RulesetChoiceForm):
    rulesets_label = "Apply transformation(s) to the following ruleset(s)"
    action = forms.ChoiceField()
    lateral = forms.ChoiceField()
    target = forms.ChoiceField()

    def __init__(self, *args, **kwargs):
        super(CategoryTransformForm, self).__init__(*args, **kwargs)
        self.fields['action'].choices = Category.get_transformation_choices(key=Transformation.ACTION)

rules/templates/rules/copy_ruleset.html
{% extends "rules/base.html" %}
{% load bootstrap3 %}

{% block sidebar %}
<div class="panel-heading">
<h2 class="panel-title">Copy ruleset "{{ object.name }}"</h2>
</div>
{% endblock %}

{% block content %}
{% if form %}
<form class="form" action="{% url 'copy_ruleset' object.id %}" method="post">{% csrf_token %}
{% bootstrap_form form %}
<input class="btn btn-primary" type="submit" value="Submit" />
</form>
{% endif %}
{% endblock %}

rules/templates/rules/delete.html
{% extends "rules/base.html" %}
{% load bootstrap3 %}
{% block sidebar %}
<div class="panel-heading">
<h2 class="panel-title">Delete object</h2>
</div>
{% endblock %}

{% block content %}

<h2 class="title">Are you sure you want to delete object {{ object.name|default:object.pk }}?</h2>

<form class="form" action={% url delfn object.id %} method="post">{% csrf_token %}
    {% bootstrap_form form %}
<button class="btn btn-primary" type="submit">
<span class="glyphicon glyphicon-trash"> Delete object</span>
</button>
</form>

{% endblock %}

rules/templates/rules/system_settings.html
{% extends "rules/base.html" %}
{% load bootstrap3  %}


{% block sidebar %}
  <div class="panel-heading">
    <h2 class="panel-title">System settings</h2>
 </div>
  <div class="panel-body">
  <p>Submit form to update Scirius system settings.</p>
</div>
{% endblock %}


{% block content %}
{% if main_form %}
<h2>System settings edition</h2>
<ul class="nav nav-tabs" role="tablist">
    <li role="main" {% if form_id == 'main' %}class="active"{% endif %}><a href="#main" aria-controls="main" role="tab" data-toggle="tab">Main</a></li>
    <li role="es" {% if form_id == 'es' %}class="active"{% endif %}><a href="#es" aria-controls="es" role="tab" data-toggle="tab">Elasticsearch</a></li>
    <li role="kibana" {% if form_id == 'kibana' %}class="active"{% endif %}><a href="#kibana" aria-controls="kibana" role="tab" data-toggle="tab">Kibana</a></li>
</ul>

<div class="tab-content">

<div role="tabpanel" class="tab-pane fade{% if form_id == 'main' %} in active{% endif %}" id="main">
<div class="container-fluid">
<div class="row">
<div class="col-md-6">
<form class="form" action="{% url 'system_settings' %}" method="post">
    {% csrf_token %}
    <input type='hidden' name='form_id' value='main'>
    {% bootstrap_field main_form.use_http_proxy show_label=False %}
    <div id="proxy_fields">
      {% bootstrap_field main_form.http_proxy %}
      {% bootstrap_field main_form.https_proxy %}
    </div>
    {% bootstrap_field main_form.use_elasticsearch %}
    <div id="es_fields">
      {% bootstrap_field main_form.custom_elasticsearch %}
      <div id="es_custom_fields">
        {% bootstrap_field main_form.elasticsearch_url %}
        <div id="es_msg_version"></div>
        <button class="btn btn-secondary" type="button" id="es_button_lb" onclick="es_check_version(); return false;">Check</button>
      </div>
    </div>
    {% bootstrap_field  main_form.comment %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">
            {% bootstrap_icon "ok" %} Submit
        </button>
    {% endbuttons %}
</form>
</div>
</div>
</div> <!-- container-fluid -->
</div> <!-- tabpanel -->

<div role="tabpanel" class="tab-pane fade{% if form_id == 'es' %} in active{% endif %}" id="es">
<div class="container-fluid">
  <div class="row">
<div class="col-md-6">
{% if main_form.use_elasticsearch.value %}
  {% include 'rules/es_clear_all.html' %}
{% else %}
Please enable Elasticsearch first.
{% endif %}
</div>
</div>
</div> <!-- container-fluid -->
</div> <!-- tabpanel -->

<div role="tabpanel" class="tab-pane fade{% if form_id == 'kibana' %} in active{% endif %}" id="kibana">
<div class="container-fluid">
<div class="row">
<div class="col-md-6">
{% if main_form.use_elasticsearch.value %}
<form class="form" enctype="multipart/form-data" action="{% url 'system_settings' %}" method="post">
    {% csrf_token %}
    <input type='hidden' name='form_id' value='kibana'>
    {% bootstrap_label "Export user dashboards" %}
    <p class="help-block">
Clicking on the button will download the user-defined dashboards.
</p>
    {% buttons %}
        <button type="submit" name="export" class="btn btn-primary">
            {% bootstrap_icon "download" %} Export
        </button>
    {% endbuttons %}
    {% bootstrap_label "Import user dashboards" %}
    <p class="help-block">
 <strong>Note:</strong> existing dashboards with same name will be overwritten.
 </p>
    {% bootstrap_field kibana_form.file show_label=False %}
    <p class="help-block">
Select a file to import dashboards from.
</p>

    {% buttons %}
        <button type="submit" name="import" class="btn btn-warning">
            {% bootstrap_icon "upload" %} Import
        </button>
    {% endbuttons %}
    {% bootstrap_label "Clear user dashboards" %}
    <p class="help-block">This will clear all user-defined dashboards.</p>
    {% buttons %}
        <span id="clear_dashboards">
	<button type="button" name="clear" class="btn btn-danger">
            {% bootstrap_icon "trash" %} Clear
        </button>
	</span>
    {% endbuttons %}
    {% bootstrap_label "Reset SN dashboards" %}
    <p class="help-block">Reset Stamus Networks dashboards to default.</p>
    {% buttons %}
        <span id="reset_dashboards">
        <button type="button" class="btn btn-danger">
            {% bootstrap_icon "refresh" %} Reset
        </button>
	</span>
    {% endbuttons %}
</form>
<!-- Modal -->
<div class="modal fade bs-example-modal-sm" id="clear_modal" tabindex="-1" role="dialog" aria-labelledby="UpdateModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="UpdateModalLabel">Delete all user dashboards</h4>
      </div>
      <div class="modal-body" id="update_text">
        Clicking on <code>Clear</code> will delete all saved user dashboards. Click on <code>Cancel</code> to abort.
      </div>
      <div class="modal-footer">

<form class="form" enctype="multipart/form-data" action="{% url 'system_settings' %}" method="post">
    {% csrf_token %}
    <input type='hidden' name='form_id' value='kibana'>
        <button type="submit" name="clear" class="btn btn-danger">
            {% bootstrap_icon "trash" %} Clear
	</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
</form>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade bs-example-modal-sm" id="reset_modal" tabindex="-1" role="dialog" aria-labelledby="UpdateModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="UpdateModalLabel">Reset Stamus Networks' dashboards</h4>
      </div>
      <div class="modal-body" id="update_text">
        Clicking on <code>Reset</code> will result in a reset to factory default of all Stamus Networks's dashboards.
 Click on <code>Cancel</code> to abort.
      </div>
      <div class="modal-footer">

<form class="form" enctype="multipart/form-data" action="{% url 'system_settings' %}" method="post">
    {% csrf_token %}
    <input type='hidden' name='form_id' value='kibana'>
        <button type="submit" name="reset" class="btn btn-danger">
            {% bootstrap_icon "refresh" %} Reset
	</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
</form>
      </div>
    </div>
  </div>
</div>

{% else %}
Please enable Elasticsearch first.
{% endif %}
</div>
</div>
</div> <!-- container-fluid -->
</div> <!-- tabpanel -->

</div> <!-- tab-content -->

<script type="text/javascript">

$("#clear_dashboards").click(function() {
	$("#clear_modal").modal('show');
});

$("#reset_dashboards").click(function() {
	$("#reset_modal").modal('show');
});

checkbox_toggle_div('#id_use_http_proxy', '#proxy_fields');
checkbox_toggle_div('#id_use_elasticsearch', '#es_fields');
checkbox_toggle_div('#id_custom_elasticsearch', '#es_custom_fields');

function es_check_version() {
$.ajax(
{
    url: "{% url 'es_check_version'%}",
    type: 'POST',
    data: {"es_url": $('#id_elasticsearch_url').val()},
    success: function(data) {
        if (!data.error) {
            var msg = "<strong>Connected to ES " + data.es_version + "</strong>";
            if (!data.es_is_good_version) {
                msg = "<strong style=\"color: #d5ab81\">Warning: this ES version " + data.es_version + " is not supported. Please install ES version " + data.es_good_version + ".x</strong>";
            }
            $("#es_msg_version").html(msg);
        } else {
          $("#es_msg_version").html("<strong style=\"color: #cb4a62\">Error: " + data.error + "</strong>");
        }
    },
});
}

</script>


{% endif %}



{% endblock %}